[package]
name = "ethsign-keyfile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethsign = "0.8.0"
serde_json = "1.0.91"
hex = "0.4.3"
clap = { version = "4.1.4", features = ["derive"] }
